---
title: "Acer_damage"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

AMH - Load packages, set your working directory, and add data AMY
```{r}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(rcompanion)


setwd("C:/Users/hrusk/Dropbox (Smithsonian)/2021_SummerInterns/EB") #amy laptop# 

damage <- read.csv("A_rubrum_damage_04Aug2021.csv")

```

EB - Packages, Working Directory, Data 
```{r}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(rcompanion)


setwd("~/Dropbox (University of Michigan)/2021_SummerInterns/EB")
damage <- read.csv("A_rubrum_damage_04Aug2021.csv")
```


Graphing function
```{r}
#barGraphStats(data=, variable="", byFactorNames=c(""))
barGraphStats <- function(data, variable, byFactorNames) {
  count <- length(byFactorNames)
  N <- aggregate(data[[variable]], data[byFactorNames], FUN=length)
  names(N)[1:count] <- byFactorNames
  names(N) <- sub("^x$", "N", names(N))
  mean <- aggregate(data[[variable]], data[byFactorNames], FUN=mean)
  names(mean)[1:count] <- byFactorNames
  names(mean) <- sub("^x$", "mean", names(mean))
  sd <- aggregate(data[[variable]], data[byFactorNames], FUN=sd)
  names(sd)[1:count] <- byFactorNames
  names(sd) <- sub("^x$", "sd", names(sd))
  preSummaryStats <- merge(N, mean, by=byFactorNames)
  finalSummaryStats <- merge(preSummaryStats, sd, by=byFactorNames)
  finalSummaryStats$se <- finalSummaryStats$sd / sqrt(finalSummaryStats$N)
  return(finalSummaryStats)
}
```

Data manipulation

```{r}

#income level to character#
damage$Income <- as.character(damage$Income)

##replace "NA"s in Forest Income Level##
damage$Income <- damage$Income %>% replace_na("None")


##remove NAs##
damage2<- na.omit(damage)

#make percent damage numeric variable#
damage2$Percent_damage <- as.numeric(damage2$Percent_damage)

##make column for herbivores##
damage2 <- damage2 %>%
  mutate(herbivore = Grasshoppers_crickets_katydids + Caterpillar_like + Hoppers + Aphids + Thrips + Herb_beetles + Whiteflies_mealybugs_scale.insects + Mirid + Larve_pinchers)

##make column for predators##
damage2 <- damage2 %>%
  mutate(predator = Pred_beetles + Assassins + Spiders + Wasps)

##create dataframe without forest##
damage3 <- damage2 %>%
  filter(Area_type == "Urban"|Area_type == "Suburban ")

##bugs 
damage4 <- damage2 %>%
  select(Tree_num, Leaf_num, predator, herbivore, Area_type) %>%
  filter(Leaf_num == "1")

damage5 <- gather(damage4, insectgroup, abundance, c(herbivore, predator), factor_key = TRUE)

```


Explore percent damage graphs

```{r}
## Percent damage vs. Area ##
EBpalette1 <- c("#FE6100", "#DC267F", "#785EF0", "#702082")
  
g1 <- ggplot(data = barGraphStats(data = damage2, variable = "Percent_damage", byFactorNames = c("Area_type")), aes(x=Area_type, y=mean, fill=Area_type)) +
    geom_bar(stat='identity', position=position_dodge(), width=0.8) +
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position = position_dodge(0.9)) +
    annotate("text", x = 1, y = 2.7 , label = "a", size = 8)+
    annotate("text", x = 2, y = 2.7 , label = "a", size = 8)+
    annotate("text", x = 3, y = 1.75, label = "b", size = 8) +
    scale_fill_manual(values = EBpalette1) + theme(legend.position = "none") + xlab("Area Type") + ylab("Percent Damage")

## g1 + theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))

g1 + theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), text = element_text(size = 24),axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)), legend.position = "none")

ggsave("damage_area1.png")
```


```{r}

## Percent damage vs. Area and Income Level ##

damage3$Income <- factor(damage3$Income, levels=c("Low", "Medium", "High", "None"))
EBpalette <- c("#FFCB05" ,"#2F65A7", "#00274C", "#00B2A9")

g3 <- ggplot(data = barGraphStats(data = damage3, variable = "Percent_damage", byFactorNames = c("Area_type", "Income")), aes(x= Area_type, y=mean, fill=Income)) +
    geom_bar(stat='identity', position=position_dodge()) +
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position = position_dodge(0.9)) +
    annotate("text", x = .7, y = 3.2, label = "a", size = 8)+
    annotate("text", x = 1, y = 1.8, label = "b", size = 8)+
    annotate("text", x = 1.3, y = 4, label = "a", size = 8) +
    annotate("text", x = 1.7, y = 3.7, label = "a", size = 8) +
    annotate("text", x = 2, y = 1.2, label = "b", size = 8) +
    annotate("text", x = 2.3, y = 1.5, label = "b", size = 8) +
    scale_fill_manual(values = EBpalette) + xlab("Area Type") + ylab("Percent Damage")

g3 + theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), text = element_text(size = 24), axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))


```


Preparing for Analysis

Test for Norm: Spoiler Alert it is not 
```{r}
shapiro.test(damage2$Percent_damage)
ggqqplot(damage2$Percent_damage)

damage2$Percent_damage_t <- transformTukey(damage2$Percent_damage)
tukey_lamda <- transformTukey(damage2$Percent_damage, returnLambda =TRUE)

shapiro.test(damage2$Percent_damage_t)

damage2$Percent_damage_log <- log(damage2$Percent_damage +1)
shapiro.test(damage2$Percent_damage_log)

##Helping Visualize the Ugly that is my data##
plot(damage2$Percent_damage_log)
hist(damage2$Percent_damage_log)

```

Load in new packages for GLM and GLMMS
```{r}

library(lme4)
library(nlme)
library(lattice)
library(effects)
library(emmeans)

```

Ana<3
```{r}
#####mod1 <- lme(Percent_damage ~ Area_type, data = damage2, random = 1|Area_type/Tree_num)


#mod0 <- lm(Percent_damage ~ Area_type, data = damage2)

#mod1 <- lme(Percent_damage ~Area_type, random = ~1|Area_type/Tree_num, data = damage2)

mod2 <- lme(Percent_damage ~ Area_type, random = ~1|Tree_num, data = damage2)

mod3 <- lme(Percent_damage ~ Area_type*Income, random = ~1|Tree_num, data = damage3)

anova(mod2) ##Fstat and p-value for mod2##
anova(mod3) ##Fstat and p-value for mod3##

#posthoc test for pairwise comparison of means##
emmeans(mod2, list(pairwise ~ Area_type), adjust = "tukey")
emmeans(mod3, list(pairwise ~ Area_type*Income), adjust = "tukey")

```



```{r}
##BUG GRAPHS##

##Herb Area Type
g4 <- ggplot(data = barGraphStats(data = damage4, variable = "herbivore", byFactorNames = c("Area_type")), aes(x=Area_type, y=mean, fill=Area_type)) +
   geom_bar(stat='identity', position=position_dodge()) +
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position = position_dodge(0.9)) +
scale_fill_manual(values = EBpalette1) + xlab("Area Type") + ylab("Herbivore Abundance") + theme(legend.position = "none")

g4 + theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))


##Pred Area Type
g5 <- ggplot(data = barGraphStats(data = damage4, variable = "predator", byFactorNames = c("Area_type")), aes(x=Area_type, y=mean, fill=Area_type)) +
    geom_bar(stat='identity', position=position_dodge()) +
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position = position_dodge(0.9)) +
scale_fill_manual(values = EBpalette1) + xlab("Area Type") + ylab("Predator Abundance") + theme(legend.position = "none")

g5 + theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))

#Pred and Herb Together
g6 <- ggplot(data = barGraphStats(data = damage5, variable = "abundance", byFactorNames = 
  c("Area_type", "insectgroup")), aes(x=Area_type, y=mean, fill=insectgroup)) +
   geom_bar(stat='identity', position=position_dodge()) +
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position = position_dodge(0.9)) + xlab("Area Type") + ylab("Abundance")

g6 + theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), legend.title=element_blank(), legend.text=element_text(size=18)) + expand_limits(y=8) +  theme(legend.position=c(.87,.9), axis.text.x=element_text(size=12, color = "black")) +
    annotate("text", x = .78, y = 1, label = "a", size = 8)+
    annotate("text", x = 1.22, y = 2, label = "a", size = 8)+
    annotate("text", x = 1.77, y = 7.5, label = "b", size = 8) +
    annotate("text", x = 2.22, y = 5.7, label = "bc", size = 8) +
    annotate("text", x = 2.77, y = 3.4, label = "ac", size = 8) +
    annotate("text", x = 3.22, y = 2.6, label = "a", size = 8)

```
```{r}
#Anovas for Bugs by Area 

herbanova <- aov(herbivore ~ Area_type, data = damage2)
summary(herbanova)

predanova <- aov(predator ~ Area_type, data = damage2)
summary(predanova)

anova3 <- aov(abundance ~ Area_type * insectgroup, data = damage5)

anova3tukey <- TukeyHSD(anova3)
anova3tukey

herbtukey <- TukeyHSD(herbanova)
herbtukey
```


Model effect of area on herbivores and predators
```{r}
library(car)

#Use generalized linear models with poisson distrubution because it is count data ##

herbivore_area <- glm(herbivore ~ Area_type, family = poisson, data = damage2)
Anova(herbivore_area)

predator_area <- glm(predator ~ Area_type, family = poisson, data = damage2)
Anova(predator_area)

```


```{r}
##Effects of Herbivores on damage##

herbivore_glm <- lm(Percent_damage ~ herbivore*Area_type, data = damage2)
summary(herbivore_lm)

predictedherbivore <- predict(herbivore_lm, interval = "confidence", level = 0.95)

EBpalette2 <- c("#DC267F", "#785EF0", "#702082")
EBpalette3 <- c("#117733", "#882255")

##Scatterplot of HERB by Area without forest##
g69 <- ggplot(damage3, aes(x = herbivore, y = Percent_damage, color = Area_type)) + 
  geom_point(shape = 1) +
  geom_smooth(method = "lm", se = FALSE, fullrange = FALSE) +
  xlab("Number of Herbivores") + ylab("Percent Damage") + scale_color_manual(values = EBpalette2) +  theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), text = element_text(size = 24),axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))

g69
```


```{r}
##Scatterplot of PRED by Area##
g420 <- ggplot(damage3, aes(x = predator, y = Percent_damage, color = Area_type)) + 
  geom_point(shape = 1) +
  geom_smooth(method = "lm", se = FALSE, fullrange = FALSE) +
  xlab("Number of Predator") + ylab("Percent Damage") + scale_color_manual(values = EBpalette2) +  theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), text = element_text(size = 24),axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))
```


```{r}
##Scatterplot of PRED by Herb##
g333 <- ggplot(damage3, aes(x = herbivore, y = predator, color = Area_type)) + 
  geom_point(shape = 1) +
  scale_colour_hue(l=50) +
  geom_smooth(method = "lm", se = FALSE, fullrange = FALSE) +
  xlab("Number of Herbivore") + ylab("Number of Predator") + scale_color_manual(values = EBpalette2) +  theme(panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), text = element_text(size = 24),axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))

```


```

