---
title: "Acer_damage"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

AMH - Load packages, set your working directory, and add data AMY
```{r}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(rcompanion)


setwd("C:/Users/hrusk/Dropbox (Smithsonian)/2021_SummerInterns/EB") #amy laptop# 

damage <- read.csv("A_rubrum_damage_04Aug2021.csv")


```

EB - Packages, Working Directory, Data 
```{r}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(rcompanion)


setwd("~/Dropbox (University of Michigan)/2021_SummerInterns/EB")
damage <- read.csv("A_rubrum_damage_04Aug2021.csv")
```


Graphing function
```{r}
#barGraphStats(data=, variable="", byFactorNames=c(""))
barGraphStats <- function(data, variable, byFactorNames) {
  count <- length(byFactorNames)
  N <- aggregate(data[[variable]], data[byFactorNames], FUN=length)
  names(N)[1:count] <- byFactorNames
  names(N) <- sub("^x$", "N", names(N))
  mean <- aggregate(data[[variable]], data[byFactorNames], FUN=mean)
  names(mean)[1:count] <- byFactorNames
  names(mean) <- sub("^x$", "mean", names(mean))
  sd <- aggregate(data[[variable]], data[byFactorNames], FUN=sd)
  names(sd)[1:count] <- byFactorNames
  names(sd) <- sub("^x$", "sd", names(sd))
  preSummaryStats <- merge(N, mean, by=byFactorNames)
  finalSummaryStats <- merge(preSummaryStats, sd, by=byFactorNames)
  finalSummaryStats$se <- finalSummaryStats$sd / sqrt(finalSummaryStats$N)
  return(finalSummaryStats)
}
```

Data manipulation

```{r}

#income level to character#
damage$Income <- as.character(damage$Income)

##replace "NA"s in Forest Income Level##
damage$Income <- damage$Income %>% replace_na("None")


##remove NAs##
damage2<- na.omit(damage)

#make percent damage numeric variable#
damage2$Percent_damage <- as.numeric(damage2$Percent_damage)


```


Explore percent damage graphs

```{r}
## Percent damage vs. Area ##
ggplot(data = barGraphStats(data = damage2, variable = "Percent_damage", byFactorNames = c("Area_type")), aes(x=Area_type, y=mean)) +
    geom_bar(stat='identity', position=position_dodge()) +
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position = position_dodge(0.9)) +
    scale_fill_brewer(palette = "Set1") +
    ylab("Percent Damage") + xlab("Area")

## Percent damage vs. Area and Income Level ##

damage2$Income <- factor(damage2$Income, levels=c("Low", "Medium", "High", "None"))

ggplot(data = barGraphStats(data = damage2, variable = "Percent_damage", byFactorNames = c("Area_type", "Income")), aes(x= Area_type, y=mean, fill=Income)) +
    geom_bar(stat='identity', position=position_dodge()) +
    geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width = 0.2, position = position_dodge(0.9)) +
    scale_fill_brewer(palette = "Set1") +
    ylab("Percent Damage") + xlab("Area Type")
```

Preparing for Analysis

Test for Norm: Spoiler Alert it is not 
```{r}
shapiro.test(damage2$Percent_damage)
ggqqplot(damage2$Percent_damage)

damage2$Percent_damage_t <- transformTukey(damage2$Percent_damage)
tukey_lamda <- transformTukey(damage2$Percent_damage, returnLambda =TRUE)

shapiro.test(damage2$Percent_damage_t)

damage2$Percent_damage_log <- log(damage2$Percent_damage +1)
shapiro.test(damage2$Percent_damage_log)

##Helping Visualize the Ugly that is my data##
plot(damage2$Percent_damage_log)
hist(damage2$Percent_damage_log)

```

Load in new packages 
```{r}

library(lme4)
library(nlme)

```

Ana<3
```{r}

mod1 <- lme(Percent_damage ~ Area_type, data = damage2, random = 1|Area_type/Tree_num)
##Object not found is the random factor##

```


